services:
  web:
    build: .
    ports:
      - "8080:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - SECRET_KEY=django-insecure-^-6a65=7qd^m-8%7sgx@r8ctz87xwe%8_v*rb3!mwszh*mh%!2
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:2321@localhost:5432/main
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume:
